name: Snapshot and Export Tables

on:
  workflow_dispatch:
    inputs:
      # ProjectID:
      #   description: 'GCP project id'
      #   required: true
      #   default: 'james-bond'
      # Dataset:
      #   description: 'BigQuery dataset'
      #   required: true
      #   default: 'dstest001'
      # GCSBucket:
      #   description: 'GCS bucket'
      #   required: true
      #   default: 'test-bucket'
      environment:
        type: choice
        description: 'environment name'
        default: 'dev'
        options: 
        - dev
        - qa
        - sandbox

jobs:
  bqSnapshot:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v2'		  
      
      # - name: Grant execute permission for the script
      #   run: chmod +x .github/workflows/snapshot-and-export.sh
      - name: Read ${{inputs.environment}}.tfvars
        id: read_tfvars
        run: |
          while IFS='=' read -r key value; do
            key=$(echo "$key" | tr -d ' ')
            value=$(echo "$value" | tr -d ' "')
            echo "$key=$value" >> $GITHUB_ENV
          done < ${{inputs.environment}}.tfvars

      - name: Print environment variables
        run: |
           echo "hello world"
      - name: Set prefix
        run: |
          #echo "prefix=${{ inputs.environment }}-${{ vars.Project_Name }}-${{ vars.ID }}" >> $GITHUB_ENV
          echo "BUCKET_NAME=${{ env.environment }}-${{ env.project_name }}-${{ env.id }}-bq-snapshot" >> $GITHUB_ENV
          echo "Dataset_ID=${{ env.environment }}-${{ env.project_name }}-${{ env.id }}ds" >> $GITHUB_ENV
          echo "ProjectID=${{ env.project }}"  >> $GITHUB_ENV
      
      - name: Run Snapshot and Export Script
        working-directory: .github/workflows
        run: |
          bash snapshot_export.sh ${{ env.ProjectID }} ${{ env.Dataset_ID }} ${{ env.BUCKET_NAME }} ${{ inputs.environment }}
